name: Testing

on:
  push:
    branches: [ master ]
  pull_request:

env:
  GO_VERSION: 1.16.4

jobs:
  build:
    name: Build
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go ${{ env.GO_VERSION }}
      uses: actions/setup-go@v2
      with:
        go-version: ${{ env.GO_VERSION }}
      id: go
    - name: setup env
      run: |
        echo "GOPATH=$(go env GOPATH)" >> $GITHUB_ENV
        echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
      shell: bash
    - name: Check out code
      uses: actions/checkout@v2
    - name: Build
      run: |
        go mod download
        go build .

  lint:
    name: Lint
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go ${{ env.GO_VERSION }}
      uses: actions/setup-go@v2
      with:
        go-version: ${{ env.GO_VERSION }}
      id: go
    - name: setup env
      run: |
        echo "GOPATH=$(go env GOPATH)" >> $GITHUB_ENV
        echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
      shell: bash
    - name: Check out code
      uses: actions/checkout@v2
    - name: Init
      run: |
        go mod download
    - name: Lint
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.39

  nancy:
    name: Sonatype Nancy
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go ${{ env.GO_VERSION }}
      uses: actions/setup-go@v2
      with:
        go-version: ${{ env.GO_VERSION }}
      id: go
    - name: Check out code
      uses: actions/checkout@v2
    - name: WriteGoList
      run: go list -json -m all > go.list
    - name: Scan by Nancy
      uses: sonatype-nexus-community/nancy-github-action@main
